- hosts: localhost
  tasks:
    # essentials:
    - include: tasks/homebrew.yml
    - include: tasks/core.yml
    # - include: tasks/dotfiles.yml

    # editor
    - include: tasks/editor/android-studio.yml
    - include: tasks/editor/atom.yml
    - include: tasks/editor/visual-studio-code.yml

    # terminal
    - include: tasks/terminal/cheat.yml
    - include: tasks/terminal/midnight-commander.yml
    - include: tasks/terminal/simplehttp2server.yml
    - include: tasks/terminal/tmux.yml

    # browser
    - include: tasks/browser/chrome.yml
    - include: tasks/browser/firefox.yml
    - include: tasks/browser/opera.yml

    # dev-tool
    - include: tasks/dev-tool/docker.yml
    - include: tasks/dev-tool/git-quick-stats.yml
    - include: tasks/dev-tool/heroku.yml
    - include: tasks/dev-tool/imageoptim.yml
    - include: tasks/dev-tool/ngrok.yml
    - include: tasks/dev-tool/npm-packages.yml
    - include: tasks/dev-tool/pgadmin4.yml
    - include: tasks/dev-tool/postgresql.yml
    - include: tasks/dev-tool/postman.yml
    - include: tasks/dev-tool/sequel-pro.yml
    - include: tasks/dev-tool/sourcetree.yml
    - include: tasks/dev-tool/virtualbox.yml

    # util
    - include: tasks/util/anki.yml
    - include: tasks/util/boostnote.yml
    - include: tasks/util/calibre.yml
    - include: tasks/util/flux.yml
    - include: tasks/util/imagemagick.yml
    - include: tasks/util/keepassxc.yml
    - include: tasks/util/qbittorrent.yml
    - include: tasks/util/spotifree.yml
    - include: tasks/util/taskwarrior.yml
    # TODO: use today script fork: https://github.com/megabitsenmzq/Today-Scripts/releases
    - include: tasks/util/today-scripts.yml
    - include: tasks/util/tresorit.yml
    - include: tasks/util/tunnelbear.yml

    # language
    - include: tasks/language/node.yml
    - include: tasks/language/python.yml
    - include: tasks/language/ruby.yml

    # chat
    - include: tasks/chat/slack.yml

    # media
    - include: tasks/media/spotify.yml
    - include: tasks/media/vlc.yml

# ADD iStat Menus
# ADD Swipes

# Extra
# Install gems
# Install global npm modules
# ADD three click dictionaries
# ADD sidebar bux states

# TODOs
# set up git user
