- name: Install core packages
  package: name={{ item }}
  with_items:
    - curl
    - git
    - htop
    - vim
    - wget
    - zsh
    - tree
    - gnutls

- name: Install apps
  homebrew_cask: name={{ item }}
  with_items:
    - amethyst
